### ISSUE TITLE
Problem when I scale in game hud to 80%

### ISSUE THREAD

**Issue by therealcrow999** [TyKonKet/FS17_FuelUsageDisplay#1]
This happens when I use the ingame slider to scale the UI smaller, I use 80%

http://s1262.photobucket.com/user/therealcrow999/media/FarmingSimulator2017Game%201-15-2017%2012-03-29%20PM-702_zps2gyqbgcw.jpg.html

http://s1262.photobucket.com/user/therealcrow999/media/FarmingSimulator2017Game%201-15-2017%2012-03-22%20PM-85_zpsrsnsmzaw.jpg.html

You can tell in the one picture when I turn on the Drive Control 4x4 and def locks, the Drive Control Icons get messed up my this mod when it gets scaled to 80%

**Comment by TyKonKet** [comment]
Hi @therealcrow999 , thanks for your report, I'll start working on this sooner as possible, meanwhile if someone want fix it, is welcome.

**Comment by TyKonKet** [comment]
This problem have been definitively fixed with 37781bd1c5e570b9f26b03f964ead8888de2489e.
