### ISSUE TITLE
Fuel consumption stuck on 0.0ltr

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#12]
After the V3.5.0 Update the fuel consumption stuck to 0.0 liters on the Terra Dos T4-40.

-I have the Gearbox-mod installed.

![20170325121730_1](https://cloud.githubusercontent.com/assets/6373374/24321783/51299dc0-1155-11e7-9208-21929d463bc5.jpg)

**Comment by TyKonKet** [comment]
Thanks for your report, I'll check as soon as possible.

**Comment by TyKonKet** [comment]
This bug is not caused by the gearbox, it exists even without the gearbox mod, I'm still investigating to understand from what is caused.

**Comment by TyKonKet** [comment]
Found and fixed.
