### ISSUE TITLE
Possible bug with gearbox

### ISSUE THREAD

**Issue by TyKonKet** [TyKonKet/FS17_FuelUsageDisplay#13]
Some players have noticed a possible bug with the gearbox mod that cause the instantaneous emptying of the tank

**Comment by ghost** [comment]
I can confirm that.

The HUD shows "inf l/h".
Then the tank is empty.

Two times happened.

**Comment by ghost** [comment]
I guess it happened when I hired AI-Worker.

**Comment by TyKonKet** [comment]
Ok, maybe it happens in different situations, because a player said me it happened while the motor load was high.

**Comment by ghost** [comment]
Well the AI-Worker runs with around 100% load.

**Comment by TyKonKet** [comment]
I'm trying to reproduce this issue but after 30 min still not reproduced...

**Comment by ghost** [comment]
Yeah it happened to me 2 times in around 20h playtime.
Is it possible to receive corrupt numbers from the game? There is a reason to calculate infinite. There must be an error somewhere.

**Comment by TyKonKet** [comment]
Maybe first of subtract the calculated number I can check if it is infinite, this should fix the problem no?

**Comment by ghost** [comment]
How sensitive is it to negative numbers?
Or set the incoming numbers into a min/max regulation. So the values couldn't leave their normal environment.

**Comment by TyKonKet** [comment]
Ok, I think with a min/max control I should fix the problem
``` lua
rpmFactor = Utils.clamp(rpmFactor, 0, 1);
loadFactor = Utils.clamp(loadFactor, 0, 1);
```

**Comment by ghost** [comment]
If it occurs with the fix again, I'll report it to you

**Comment by TyKonKet** [comment]
Thank you so much, anyway I'll test it in the next days.
