### ISSUE TITLE
idle calculation?

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#15]
The fuel consumption is much higher with parking brake.

Parking brake , 0 km/h, **1000 RPM, "10% load"** = 6.1 l/h
Just standing , 0 km/h, **850 RPM, 0% load** = 1.8 l/h

I guess this is a big difference for nothing.

*Using the Gearbox mod
![20170326195455_1](https://cloud.githubusercontent.com/assets/6373374/24333758/528c921c-125e-11e7-8b81-6685b520e26f.jpg)
![20170326195507_1](https://cloud.githubusercontent.com/assets/6373374/24333759/5290ad16-125e-11e7-98f9-a82386fac8ed.jpg)

**Comment by TyKonKet** [comment]
You are even right, but rpm and motor load are calculated from the gearbox not from the fuel usage, the bug isn't of the fuel usage.
Any suggestions?

**Comment by ghost** [comment]
Maybe there is a way with an Workaround.

Let's examine the situation.

- Idle RPM in parking brake is fixed but can be lower when releasing the brake
- The clutch is fully opened. 0% or 0,00.
- The Vehicle speed is zero. Maybe some trembling around zero?
- The load is 0% or 10%. Then push it down and care about negative numbers.

Something like this?

```
if ((motor_RPM < (motor_RPM_min+(motor_RPM_min*0,1))) && (gearbox_clutch < 0,01) && (gearbox_load < 0,11) && (vehicle_speed < 1))
    {
        float fictional_motorRPM = actual_motorRPM * 0,85;    //factor maybe 0,85 or something
        float fictional_motorLoad = (sqrt(actual_motorLoad - 0,1)^2); //sqrt(x²) for eliminate a possible negative number

        //use the fictional values for calculating the idle consumption
    }
```

What do you think?

**Comment by TyKonKet** [comment]
Seems to be a possible solution, I'll work on it today.

**Comment by ghost** [comment]
I'm curious :)

**Comment by TyKonKet** [comment]
I found a possible bug with this workaround, if you turn on a pto implement while you are standing, his motor load will be eliminated.
