### ISSUE TITLE
Wobbling calculations

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#16]
I just tapped the key "W"

https://youtu.be/rRaf_o2bIS0

After a few seconds the fuel calculation has normalized.

actual version:

https://github.com/TyKonKet/FS17_FuelUsageDisplay/commit/6a1bc8db1ccade6d99189567d0a4c917b0e2a677

**Comment by ghost** [comment]
Strange
I could not reproduce this

**Comment by ghost** [comment]
Now I could reproduce this multiple times.

**Comment by TyKonKet** [comment]
This bug happens only with terra variant?

**Comment by ghost** [comment]
Yes. But i have an idea.
I've installed the Ground Response Mod 
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=52696&title=fs2017

As you can see, my Holmer is full with Wheat. So the vehicle weighs several tons.
The ground can cause this heavy wobbling load.

Edit:
Maybe the indication is too sensitive to frequent load changes.
A cool thing could be an additional indicator for long time average consumption.

Edit2:
The Fendt 939 works with a trailer as he should. No wobbling.

**Comment by TyKonKet** [comment]
I can't reproduce this bug even with gearbox and ground response, are you sure this is not an issue of your version of gearbox?

**Comment by ghost** [comment]
I'll try it

**Comment by ghost** [comment]
Ok with Gearbox 2.0.4.4 I couldn't reproduce it either.
Then forget it. There is no bug to take care of.  😋 

Edit:
But an average fuel consumption indicator would still be an enrichment

**Comment by TyKonKet** [comment]
I know, but I have no Idea where to locate it 😃

**Comment by ghost** [comment]
example code incoming

✈️ 

```
while(true)
{
	average_consumption = (average_consumption + actual_consumption)/2;
	wait(10sec);
}
```

**Comment by TyKonKet** [comment]
Yes, but where should I place the text on the hud?

**Comment by ghost** [comment]
Take a look on this:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=70368&title=fs2017

or this old mod:
https://www.modhoster.com/mods/kraftstoff-verbrauchsanpassung-fueladjust#images

**Comment by ghost** [comment]
This issue could be closed no?
I mean, it's already fixed
:sunglasses:
