### ISSUE TITLE
3 different fuel consumption values

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#17]
😲 

![20170329201629_1](https://cloud.githubusercontent.com/assets/6373374/24470007/b7395716-14bd-11e7-988f-764494d3d6f3.jpg)

used version:
https://github.com/TyKonKet/FS17_FuelUsageDisplay/commit/d8ca40cfd6a81d64065c2d7c959394962b4b4e75

**Comment by TyKonKet** [comment]
Don't look at the top left values, they are values used by me for debugging purposes.
About gearbox values, I'm still working on it.

**Comment by ghost** [comment]
![20170330183915_1](https://cloud.githubusercontent.com/assets/6373374/24515717/bafd06ac-1578-11e7-904d-f3f9239044d9.png)
