### ISSUE TITLE
combine harvester - cutter uses too much power

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#19]
The combine harvesters are very weak on the mountain. Is this really so extreme in reality?
Some harvesters are only by the cutting mechanism (without driving) already on 100% load.
600PS can't get faster than 5 km/h on a small slope. The average speed is ~3km/h.

There is no difference between a 200ps and a 600ps combine harvester.

**Comment by TyKonKet** [comment]
Don't worry, I'm still working on balancing of various values.

**Comment by TyKonKet** [comment]
After lots of tests on this, I conclude that this is a bug caused by Gearbox and not from Better Fuel Usage, I tried to remove the Gearbox and the problem have been solved, instead if I deactivate the Better Fuel Usage and leave the Gearbox, the bugs remains.
