### ISSUE TITLE
 Vehicles are more economical with more RPM

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#20]
- 2100 RPM - 90% load - **69l/h**
- 1650 RPM - 100% load - **74l/h**

If I am not mistaken, engines with more RPM will also consumes more fuel.
Not the other way around.

![20170331194038_1](https://cloud.githubusercontent.com/assets/6373374/24562183/343a7b36-164a-11e7-9ff7-3c3435e88b04.jpg)
![20170331194026_1](https://cloud.githubusercontent.com/assets/6373374/24562182/34393cd0-164a-11e7-8e9d-4c0b976a89a2.jpg)

*I don't know what this (eco) thing is. Makes no difference. 💃

**Comment by ghost** [comment]
- 690 RPM - 0% load - **3,6 l/h**
- 1790 RPM - 0% load - **3,6 l/h**

![20170331200403_1](https://cloud.githubusercontent.com/assets/6373374/24563004/3a63613c-164d-11e7-891c-42573a932f80.jpg)
![20170331200409_1](https://cloud.githubusercontent.com/assets/6373374/24563005/3a815e26-164d-11e7-8d32-b0a76dcf01d6.jpg)

**Comment by TyKonKet** [comment]
Ask to gearbox creator how is possible that an engine runs at 1790 RPM without load 😃

**Comment by ghost** [comment]
It's a feature 🐛 
Hand Throttle ;)
https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Description.pdf
