### ISSUE TITLE
bale collector causes no load

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#21]
https://www.youtube.com/watch?v=WFQB8mw5Wfg&feature=youtu.be

**Comment by ghost** [comment]
The other bale thing has the same issue

![20170331225207_1](https://cloud.githubusercontent.com/assets/6373374/24569063/c2e09cca-1664-11e7-9b18-81fc485114a0.jpg)

**Comment by TyKonKet** [comment]
Ok thanks, I'll work on this in the next few days.

**Comment by ghost** [comment]
Same issue with Selfline compact 1612

**Comment by ghost** [comment]
Trailer special function
https://youtu.be/IRKCzms4Oxg

**Comment by TyKonKet** [comment]
11d63d969d77ee5fe5a8c623dfd1dfb9192178af
ea2cfcf49529dd1101132b89d5de7fc97be8fcb3

**Comment by ghost** [comment]
Siloking Compact 1612
same issue :p

**Comment by TyKonKet** [comment]
I forgot of it, vehicle and implement types are lots, sorry if I forgot some of them and thanks for your help.
