### ISSUE TITLE
tools - load does not return to 0%

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#22]
It happens with every tool.
Not always. But often.

![20170401192408_1](https://cloud.githubusercontent.com/assets/6373374/24580888/da385848-1710-11e7-9b73-f4ca9ed87a32.jpg)
![20170401192648_1](https://cloud.githubusercontent.com/assets/6373374/24580905/2b3c20d0-1711-11e7-85af-a83137ebb800.jpg)
![20170401192726_1](https://cloud.githubusercontent.com/assets/6373374/24580907/410fef0e-1711-11e7-9f96-dd75793373f3.jpg)
![20170401192918_1](https://cloud.githubusercontent.com/assets/6373374/24580920/83926d52-1711-11e7-97e3-9b6f69cfa2dc.jpg)

**Comment by TyKonKet** [comment]
This bug should now be fixed.
