### ISSUE TITLE
JCB 435S has no hydraulics calculation

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#23]
JCB 435S has no hydraulics calculation

**Comment by TyKonKet** [comment]
Are you sure? It works for me.

**Comment by ghost** [comment]
oh.. shame on me
My mod was some commits older. It works with rc1 https://github.com/TyKonKet/FS17_FuelUsageDisplay/commit/eb02359901117fa3125648a871566defa9f75264 now.

In future I do not report bugs this quick.

**Comment by TyKonKet** [comment]
Don't worry 😄
