### ISSUE TITLE
Bug with Foldable.lua

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#25]
Game Log
Bug freeze the game

> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:34: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'packetReceived'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:45: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'update'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:34: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'packetReceived'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:45: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'update'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:34: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'update'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:34: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'packetReceived'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:45: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)
> Error: Running LUA method 'update'.
> D:/home/sid/farmingSim_2017/profile/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:34: attempt to perform arithmetic on field 'foldMiddleAnimTime' (a nil value)

**Comment by TyKonKet** [comment]
Happened with what implement?

**Comment by ghost** [comment]
Modded Liquid manure
