### ISSUE TITLE
Different consumption with different vehicles but same tools

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#26]
```
Tool: Jenz HEM 583 Z

CASE IH Magnum
77 l/h

CASE IH Quadrac
114 l/h

Fendt 939
68 l/h
```

The consumption should be similar. 
Rather less if the engine is stronger. And thus more efficient.

_The same happens with other tools._

Edit:
PTO shaft work

**Comment by TyKonKet** [comment]
This is not totally right, because every tool require a specific pto speed, and the motor speed needed to reach this specific pto speed is almost the same on all tractors.
So the fuel needed depends for the most from the vehicle maximum consumption.

**Comment by ghost** [comment]
But don't you think the difference is too high? Yes the Engines have different power. Yes the pto RPM is the same. 
Nevertheless, the engine is subject to the same load with different capacities. So they should have a similar consumption.

> So the fuel needed depends for the most from the vehicle maximum consumption.

If you mean that is correct then every strong tractor is uneconomical.


An example:

We have a load which needs 100kW.

We have a motor with 300kW power.
And we have a motor with 400kW power.

Both motors are loaded with 100kW. Why should one engine need much more fuel?
There is a difference because the motors are differently efficient. With the same load, the difference is slight.

**Comment by ghost** [comment]
Take a look a the jenzHEM583.xml

```
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicle type="woodCrusherTrailer">
    <annotation>Copyright (C) GIANTS Software GmbH, All Rights Reserved.</annotation>

    <storeData>
        <name>HEM 583 Z</name>
        <specs>
            <neededPower>250</neededPower>
        </specs>
        <functions>
            <function>$l10n_function_forestryWoodCrusher</function>
        </functions>
        <rotation>0</rotation>
        <image>data/store/store_jenzHEM583.png</image>
        <price>88000</price>
        <dailyUpkeep>130</dailyUpkeep>
        <lifetime>600</lifetime>
        <brand>JENZ</brand>
        <category>wood</category>
        <vertexBufferMemoryUsage>1045192</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>158754</indexBufferMemoryUsage>
        <textureMemoryUsage>17651416</textureMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>
    </storeData>

    <typeDesc>$l10n_typeDesc_woodCrusher</typeDesc>
    <filename>data/vehicles/trailers/jenz/jenzHem583.i3d</filename>

    <size width="3.5" length="7" />

    <powerConsumer ptoRpm="600" neededPtoPower="180"/>

```

neededPtoPower="180"

**Comment by TyKonKet** [comment]
Is the same of the idle consumption, why they are different even if the load is 0% for all vehicles?
As I already said, the fuel consumption depends for the most from the RPM, I don't know if you have an idea of how the engine is made and works, but I suggest to take a look at the injection phase of engines.
I know the needed pto power is the same because of the implement is the same, but it is the needed pto power, not the consumed pto power.
Needed pto power, means the minimum power of the vehicle required to startup the implement. The consumed pto power depends from many factors and many work situations.

**Comment by TyKonKet** [comment]
However, we are still talking, but we might as well stop because even if you're right I could still do anything since the load and engine speed calculations are made by GIANTS Engine so I can not change them.

**Comment by fcelsa** [comment]
Always we talk about game with some compromises and limitations, on other hand it's true! a great power tractor not are the best solution in any case, the variable it's still the work that one needs to do, and find all correct compromises in the dimension and engine power, so the actual Fuel calculation can be considered correct IMHO; I never move the jenz with quadtrac, it is clear that it would be uneconomical, at the same time, a tractor with 200=220 hp can be around the limit, depends also what type of goods I need to grind, but there is not in game problem ;)

**Comment by TyKonKet** [comment]
@mieperDE , you should also consider that you are playing and testing all with the gearbox active, that influences very much all motor calculations, if you try the same without the gearbox, you will see that consumption differences are not that much big.

```
Tool: Jenz HEM 583 Z

CASE IH Magnum
47 l/h

CASE IH Quadrac
50 l/h

Fendt 939
46 l/h
```
Do you like this much more, you must choose if use or not the Gearbox.

**Comment by ghost** [comment]
This looks much better.
Then I will talk with mogli.
:smile:
