### ISSUE TITLE
Changelogs translations needed

### ISSUE THREAD

**Issue by TyKonKet** [TyKonKet/FS17_FuelUsageDisplay#27]
Hi @mieperDE, @naej56, @Gonimy-Vetrom, @Dzi4d3k , @FarmingVidsHD.  
The new version of Better Fuel Usage ( V3.6.1) is almost ready, I would be glad if you could translate the changelogs.

**Comment by ghost** [comment]
done :relieved:

**Comment by FarmingVidsHD** [comment]
Dutch is Done
