### ISSUE TITLE
Issue with Köckerling Allrounder

### ISSUE THREAD

**Issue by Brandox1992** [TyKonKet/FS17_FuelUsageDisplay#31]
Hello :)
first of all nice mod i like to use this mod for the realness.
now the problem.
since the update which i installed today i wanted to cultivate with the "Köckerling Allrounder" and had to find out that the machine bounces in the air when you put them in the ground and you drive.
would be nice if you fix that :)

best regards.
Marcel aka Brandox

**Comment by TyKonKet** [comment]
Hi, @Brandox1992 I found the same issue some time ago, but I tried remove the Better Fuel Usage and the problem haven't been solved, so I thought the problem wasn't caused by this mod.

**Comment by Brandox1992** [comment]
before the update and with the old version the problem wasn't there, so it has something to do with the new update i think.
i tried the other cultivators but the köckerling is the only one with that problem @TyKonKet

**Comment by TyKonKet** [comment]
Ok, I'll investigate on that

**Comment by Brandox1992** [comment]
Okay nice @TyKonKet
