### ISSUE TITLE
Issue with NewHolland FR850

### ISSUE THREAD

**Issue by Fendtfan84** [TyKonKet/FS17_FuelUsageDisplay#32]
Bye this Forage harvesters This message appears in the log bye Maize choping.
This error message came when the CombineAddon Mod with FuelUsageDisplay in the mod folder is
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/Foldable.lua(716) : attempt to compare nil with number
I Have the Mod new installed and the error message is path.
The issue can closed

**Comment by MichaelSGallagher** [comment]
Ya there seems to be some issues around Foldable.lua and Foldable mods within FS17. For example in my error log:

`C:/Users/thewi/Documents/My Games/FarmingSimulator2017/mods/Horsch_Pronto15m/pronto18DC.i3d (433.17) ms
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Users/thewi/Documents/My Games/FarmingSimulator2017/mods/FS17_FuelUsageDisplay/extensions/Foldable.lua:11: attempt to index local 'anim' (a nil value)`

The Horsch Pronto 15m has been around for awhile and a great mod. I am assuming that with the latest FS17 patches and how animations are done now there is some clashing with pulling how many animated parts there are on mods the way your lua code is trying to read it in for power consumption.

For Temporary workaround, I just commented out this line in moDesc.xml until a fix is found:

` <!-- <sourceFile filename="extensions/Foldable.lua"/> -->`

Everything else works just fine when this is done. This error will even prevent some mods from being purchased in the store if they have some sort of foldable parts such as the Bednar Pro Seeder v3

**Comment by TyKonKet** [comment]
Hi guys, sorry for the late response, I received other reports about similar issues with Foldable.lua, I will fix that in the next version but I haven't any idea when I'll find time for work on it, currently I'm hard working on the mod for the Fs17 Mod Contest.
@MichaelSGallagher your workaround is a good temporary solution while waiting for the next version.

**Comment by TyKonKet** [comment]
Ok, test done with **Horsch_Pronto15m/pronto18DC**, now it works!
