### ISSUE TITLE
rippers behind the tractor bounce over the field with FuelusageDisplay 3.6.2

### ISSUE THREAD

**Issue by ometinsu** [TyKonKet/FS17_FuelUsageDisplay#34]
When i use the YMPA SJ Series V.1.2.2.0 mod, the ripper bounces over the field, and when i go back to the 3.6.1 version of the FuelusageDisplay one of my savegames won't load anymore and other don't work at all.
Is this a problem in de FuelusageDisplay 3.6.2 or is something else to blame?

**Comment by TyKonKet** [comment]
I can't say nothing about old versions without reading the log, but i can fix the problem with your tool in the next version if you send me the download link.

**Comment by ometinsu** [comment]
Thank your for the fast reponse.
FuelusageDisplay 3.5.0 does work with YMPA SJ Series V.1.2.2.0 mod, without bouncing all over the field.
I have also the John Deere 915 ripper with the same problem with FuelusageDisplay 3.6.2, but with the FuelusageDisplay 3.5.0 it is fine.
So between the 3.5.0 en the 3.6.x something changed that caused the issue.

The links to the mods are:
https://www.modland.net/farming-simulator-2017-mods/implements-tools/jympa-sj-series-v-1.2.2.html 
https://www.modland.net/farming-simulator-2017-mods/implements-tools/john-deere-915-v-ripper.html
