### ISSUE TITLE
Fuel consumption with Helper and "Buy Fuel" option

### ISSUE THREAD

**Issue by TyKonKet** [TyKonKet/FS17_FuelUsageDisplay#36]
Hi @Mogli12, when your mod is active and the Motorized:updateFuelUsage is yours, if the helper is hired and it is setted for buying fuel instead of consume it, I can't display the instant fuel usage.
Can you please set this value on a variable even when the helper is hired?

**Comment by Dzi4d3k** [comment]
Just to make information consistent for others, here is answer from Mogli12:

> I do not know how Dural implemented it. In the GearboxAddon I calcualte the fuel consumption based on motor data. I the vehicle is hired and the setting is to buy fuel I calculate the amount and subtract it from the shared money. 
>The fuel consumption display in GearboxAddon really checks the different fuel levels. Since there is no fuel take the rate will be 0.0 l/h.

https://www.fs-uk.com/forum/index.php?topic=195659.msg1283074#msg1283074

**Comment by TyKonKet** [comment]
From Mogli12:
GearboxAddon 2.1.3.8 hides the display of fuel usage if the motor is off or the hired worker is on and buys fuel. I do not want to send additional data via read-/writeUpdateStream just to solve this problem. I think read-/writeUpdateStream should not be used too intense.
