### ISSUE TITLE
Fuel Usage x2

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [TyKonKet/FS17_FuelUsageDisplay#38]
Hey. Please look at this issues https://github.com/Mogli12/GearboxAddon/issues/249.

**Comment by Mogli12** [comment]
Hi,
With a recent version of GearboxAddon you can use the following function to read the fuel rate:
```lua
local rate = 0
if type( self.mrGbMGetFuelUsageRate ) == "function" and self:mrGbMGetIsOn() then
  rate = self:mrGbMGetFuelUsageRate()
end
```

**Comment by TyKonKet** [comment]
Hi, thank you for the hint, I'll fix it as soon as possible.
Currently i'm working on the DLC so I haven't much time but i'll try to roll up a new version fast.

**Comment by Dwinesk** [comment]
Hi,
Are you still planning on making this fix? I hope so. Thanks for the mod and all your good work.

**Comment by TyKonKet** [comment]
Yes, but to be honest at the moment I'm working on the Grimme DLC and we must end it in the planned times, so i have not enough time to work on it, maybe in the next months the new update will be ready.

**Comment by Dwinesk** [comment]
Thank you.

**Comment by Mogli12** [comment]
Can we please keep this issue opened? In my opinion closing such issue means that the problem is fixed and not that there is no time to fix it.

**Comment by Dzi4d3k** [comment]
@Mogli12 but https://github.com/TyKonKet/FS17_FuelUsageDisplay/commit/a7622d170df4af49d15280dc183c192a358d260c didn't fixed this issue?

**Comment by TyKonKet** [comment]
@Dzi4d3k yes it does.
Any way I haven't closed it, it have been closed automatically when i referenced it in the commit 😄

**Comment by Mogli12** [comment]
Ok, I did not know that it is possible to close an issue with a commit. Then it should be ok.

**Comment by TyKonKet** [comment]
@Mogli12 I just found out xD

**Comment by Gonimy-Vetrom** [comment]
Thank you and from me. Everything is working. 
Success in working with DLC.
