### ISSUE TITLE
Dominator for the second time

### ISSUE THREAD

**Issue by MPosp** [TyKonKet/FS17_FuelUsageDisplay#40]
Greetings and thanks for the latest edits, the Claas Dominator 118SL now works perfectly. However, as it follows from the screenshot I attach, it does not consume any fuel at all. :-)
![fsscreen_2017_11_22_20_02_36](https://user-images.githubusercontent.com/33684063/33162197-7abe202e-d028-11e7-8190-996b6e69db1b.png)

**Comment by TyKonKet** [comment]
Sorry my fault.
