### ISSUE TITLE
GearboxAddon

### ISSUE THREAD

**Issue by cater901645** [TyKonKet/FS17_FuelUsageDisplay#41]
Gibt es Probleme mit Diesem Mod?
Jedesmal wenn ich ein Fahrzeug kaufen möchte ohne Gearbox (off)
bekomme ich einen Fehler.
Error: Running LUA method 'update'.
C:/Users/Cater2/Documents/My Games/FarmingSimulator2017/mods-test/FS17_FuelUsageDisplay/specializations/betterFuelUsage.lua:235: attempt to index field 'mrGbMS' (a nil value)

**Comment by TyKonKet** [comment]
Can you please provide more information about this problem, most probably this is a bug.

**Comment by cater901645** [comment]
what information do you need?

[log.txt](https://github.com/TyKonKet/FS17_FuelUsageDisplay/files/1547893/log.txt)

**Comment by TyKonKet** [comment]
What version of gearbox are you running?

**Comment by cater901645** [comment]
Gearbox v3.0 build 302 by mogli

https://github.com/Mogli12/GearboxAddon

**Comment by TyKonKet** [comment]
#44
