### ISSUE TITLE
Issue with Fuel Usage display

### ISSUE THREAD

**Issue by Eloff7** [TyKonKet/FS17_FuelUsageDisplay#42]
Log file reads: "
C:/Users/EloffG/Documents/My Games/FarmingSimulator2017/mods/FS17_FuelUsageDisplay/specializations/betterFuelUsage.lua:235: attempt to index field 'mrGbMS' (a nil value)
Error: Render device Error: Unknown.
Error: Running LUA method 
[log.txt](https://github.com/TyKonKet/FS17_FuelUsageDisplay/files/1639332/log.txt)

Please can you check this, I think the problem is with the more realism mod, or the more realism mod database. Really like this mod so can you please investigate???

**Comment by TyKonKet** [comment]
Are you also using the gearbox addon?

**Comment by Eloff7** [comment]
yes
also with some gearbox addon mods

**Comment by Eloff7** [comment]
the faulty mods have been removed ie: bbm hook truck, fs17-man tgs but the fault remains

**Comment by TyKonKet** [comment]
#44
