### ISSUE TITLE
Gearbox addon

### ISSUE THREAD

**Issue by MOOOOs** [TyKonKet/FS17_FuelUsageDisplay#44]
When i buy tractor without gearbox my keyboard not working anymore and only thing to do is close game with win key and close program. Both mods up to date. please fix this.

**Comment by fdanapfel** [comment]
Try the latest version of the GearBox Add-on from https://github.com/Mogli12/GearboxAddon

There was recently a fix done in relation to the FS17_FuelUsageDisplay mod:
https://github.com/Mogli12/GearboxAddon/commit/eff1f8d39eb86380db53a527bc0ed801b0171289

**Comment by MOOOOs** [comment]
its fixed in development version thanks.
