### ISSUE TITLE
Translation works

### ISSUE THREAD

**Issue by TyKonKet** [TyKonKet/FS17_FuelUsageDisplay#5]
Hi @Gonimy-Vetrom, @naej56 and @FarmingVidsHD.
I'm going to release V3.5.0 of Fuel Usage and then I've added changelogs to modDesc.
If and when you'll have time, can you please take a final look at translations and translate changelogs in your language?

**Comment by naej56** [comment]
Hi guys, translate for changelogs in french done.
Have a nice day.

**Comment by Gonimy-Vetrom** [comment]
Need translation  betterFuelUsage.lua line 81
self.lhText = DynamicText:new({size = 0.0112, text = **" l/h"**, color = {r = 0.0865, g = 0.0865, b = 0.0865, a = 1}});

**Comment by TyKonKet** [comment]
You are right.

**Comment by naej56** [comment]
No need to modify translate for french, it's already the right one.

**Comment by FarmingVidsHD** [comment]
Hello Guys. Translation for changelogs and another things in Dutch done.

Have a good day.

**Comment by TyKonKet** [comment]
Thank you all guys!
